using System.Collections.Generic;

public class Station
{
    public string Name { get; set; }
    public string Code { get; set; }

    public Station(string name, string code)
    {
        Name = name;
        Code = code;
    }

    public override string ToString()
    {
        return $"{Name} ({Code})";
    }

    // Method to get predefined list of stations
    public static List<Station> GetStations()
    {
        return new List<Station>
        {

new Station("ABU ROAD", "ABR"),
new Station("ADILABAD", "ADB"),
new Station("ADONI", "AD"),
new Station("ADRA", "ADRA"),
new Station("AGARTALA", "AGTL"),
new Station("AGRA FORT", "AF"),
new Station("AGRA CANTT.", "AGC"),
new Station("AHMADNAGAR", "ANG"),
new Station("AHMEDABAD", "ADI"),
new Station("AJMER", "AII"),
new Station("AJNI", "AJNI"),
new Station("AKOLA", "AK"),
new Station("ALIGARH", "ALJN"),
new Station("ALIPURDUAR Jn.", "APDJ"),
new Station("ALLAHABAD", "ALD"),
new Station("ALAPPUZHA", "ALLP"),
new Station("ALNAWAR Jn.", "LWR"),
new Station("ALUVA", "AWY"),
new Station("ALWAR", "AWR"),
new Station("AMALNER", "AN"),
new Station("AMB ANDAVRA", "AADR"),
new Station("AMBALA CANTT.", "UMB"),
new Station("AMBIKAPUR", "ABKP"),
new Station("AMLA", "AMLA"),
new Station("AMRITSAR", "ASR"),
new Station("ANAKAPALLE", "AKP"),
new Station("ANAND", "ANND"),
new Station("ANAND NAGAR", "ANDN"),
new Station("ANAND VIHAR TERMINUS", "ANVT"),
new Station("ANANTAPUR", "ATP"),
new Station("ANGUL", "ANGL"),
new Station("ANNAVARAM", "ANV"),
new Station("ANUPPUR", "APR"),
new Station("ARA", "ARA"),
new Station("ARAKKONAM", "AJJ"),
new Station("ARSIKERE", "ASK"),
new Station("ASANSOL", "ASN"),
new Station("AUNRIHAR", "ARJ"),
new Station("AURANGABAD", "AWB"),
new Station("AYODHYA", "AY"),
new Station("AZAMGARH", "AMH"),
new Station("AZIMGANJ Jn.", "AZ"),
new Station("BADARPUR", "BPB"),
new Station("BADNERA Jn.", "BD"),
new Station("BAGALKOT", "BGK"),
new Station("BAGHPAT ROAD", "BPM"),
new Station("BAIDYANATHDHAM", "BDME"),
new Station("BAKTHIYARPUR", "BKP"),
new Station("BALASORE", "BLS"),
new Station("BALAGHAT", "BTC"),
new Station("BALANGIR", "BLGR"),
new Station("BALUGAON", "BALU"),
new Station("BALURGHAT", "BLGT"),
new Station("BALHARSHAH", "BPQ"),
new Station("BALLIA", "BUI"),
new Station("BANARHAT", "BNQ"),
new Station("BANDA Jn.", "BNDA"),
new Station("BANDEL Jn.", "BDC"),
new Station("BANDIKUI Jn.", "BKI"),
new Station("BANDRA (T)", "BDTS"),
new Station("BANGALORE CITY", "SBC"),
new Station("BANGALORE CANTT.", "BNC"),
new Station("BANGARAPET", "BWT"),
new Station("BANGRIPOSI", "BGY"),
new Station("BANKURA", "BQA"),
new Station("BANMANKHI", "BNKI"),
new Station("BAPATLA", "BPP"),
new Station("BARABANKI Jn.", "BBK"),
new Station("BARABIL", "BBN"),
new Station("BARAN", "BAZ"),
new Station("BARAUNI Jn.", "BJU"),
new Station("BARAUT", "BTU"),
new Station("BARAPALLI", "BRPL"),
new Station("BARDDHAMAN Jn.", "BWN"),
new Station("BAREILLY", "BE"),
new Station("BARGARH ROAD", "BRGA"),
new Station("BARHNI", "BNY"),
new Station("BARKAKANA", "BRKA"),
new Station("BARMER", "BME"),
new Station("BAROG", "BOF"),
new Station("BARSOI", "BOE"),
new Station("BARWADIH", "BRWD"),
new Station("BASAR", "BSX"),
new Station("BASTI", "BST"),
new Station("BATHINDA Jn.", "BTI"),
new Station("BAYANA", "BXN"),
new Station("BEAS", "BEAS"),
new Station("BEAWAR", "BER"),
new Station("BELAPUR", "BAP"),
new Station("BELGAUM", "BGM"),
new Station("BELLARY Jn.", "BAY"),
new Station("BETTIAH", "BTH"),
new Station("BETUL", "BZU"),
new Station("BHADOHI", "BOY"),
new Station("BHADRAK", "BHC"),
new Station("BHAGALPUR", "BGP"),
new Station("BHAGAT KI KOTHI", "BGKI"),
new Station("BHARATPUR", "BTE"),
new Station("BHARUCH", "BH"),
new Station("BHATAPARA", "BYT"),
new Station("BHATKAL", "BTJL"),
new Station("BHATNI", "BTT"),
new Station("BHAVNAGAR (T)", "BVC"),
new Station("BHAWANIPATNA", "BWPI"),
new Station("BHILWARA", "BHL"),
new Station("BHIMAVARAM Jn.", "BVRM"),
new Station("BHIMAVARAM TOWN", "BVRT"),
new Station("BHIND", "BIX"),
new Station("BHIWANI", "BNW"),
new Station("BHOPAL", "BPL"),
new Station("BHUBANESWAR", "BBS"),
new Station("BHUJ", "BHUJ"),
new Station("BHUSAVAL", "BSL"),
new Station("BIJAPUR", "BJP"),
new Station("BIJNOR", "BJO"),
new Station("BIKANER", "BKN"),
new Station("BILASPUR Jn.", "BSP"),
new Station("BINA", "BINA"),
new Station("BINNAGURI", "BNV"),
new Station("BIRUR", "RRB"),
new Station("BITRAGUNTA", "BTTR"),
new Station("BIYAVARA RAJGARH", "BRRG"),
new Station("BOBBILI", "VBL"),
new Station("BOINDA", "BONA"),
new Station("BARAPALLI", "BRPL"),
new Station("BAGHBAHAR", "BGBR"),
new Station("BOKARO STEEL CITY", "BKSC"),
new Station("BOLPUR SHANTINIKETAN", "BHP"),
new Station("BORIVALI", "BVI"),
new Station("BOTAD", "BTD"),
new Station("BUDAUN", "BEM"),
new Station("BUNDI", "BUDI"),
new Station("BURHANPUR", "BAU"),
new Station("BURHWAL", "BUW"),
new Station("BUXAR", "BXR"),
new Station("CANACONA", "CNO"),
new Station("CHAKIA", "CAA"),
new Station("CHAKKI BANK", "CHKB"),
new Station("CHAKRADHARPUR", "CKP"),
new Station("CHALISGAON", "CSN"),
new Station("CHAMPA", "CPH"),
new Station("CHANDAUSI", "CH"),
new Station("CHANDERIYA", "CNA"),
new Station("CHANDIGARH", "CDG"),
new Station("CHANDIL", "CNI"),
new Station("CHANDRAPUR", "CD"),
new Station("CHANDRAPURA", "CRP"),
new Station("CHAPARMUKH", "CPK"),
new Station("CHATRAPUR", "CAP"),
new Station("CHENGALPATTU Jn.", "CGL"),
new Station("CHENGANNUR", "CNGR"),
new Station("CHENNAI CENTRAL", "MAS"),
new Station("CHENNAI EGMORE", "MS"),
new Station("CHHAPRA", "CPR"),
new Station("CHHINDWARA", "CWA"),
new Station("CHIDAMBARAM", "CDM"),
new Station("CHIKJAJUR", "JRU"),
new Station("CHIPLUN", "CHI"),
new Station("CHIRALA", "CLX"),
new Station("CHITRAKOOTDHAM KARVI", "CKTD"),
new Station("CHITTARANJAN", "CRJ"),
new Station("CHITTAURGARH", "COR"),
new Station("CHITTOOR", "CTO"),
new Station("CHOPAN", "CPU"),
new Station("CHUNAR", "CAR"),
new Station("CHURU", "CUR"),
new Station("COIMBATORE JN.", "CBE"),
new Station("COONOOR", "ONR"),
new Station("CUDDALORE PORT", "CUPJ"),
new Station("CUDDAPAH", "HX"),
new Station("CUTTACK", "CTC"),
new Station("DADAR", "DR"),
new Station("DAHANU ROAD", "DRD"),
new Station("DAHOD", "DHD"),
new Station("DALGAON", "DLO"),
new Station("DALTONGANJ", "DTO"),
new Station("DALLIRAJHARA", "DRZ"),
new Station("DAMOH", "DMO"),
new Station("DANAPUR", "DNR"),
new Station("DARBHANGA", "DBG"),
new Station("DAUND", "DD"),
new Station("DAVANGERE", "DVG"),
new Station("DEHRADUN", "DDN"),
new Station("DEHRI-ON-SONE", "DOS"),
new Station("DELHI", "DLI"),
new Station("DELHI CANTT.", "DEC"),
new Station("DELHI SARAI ROHILLA", "DEE"),
new Station("DELHI SHAHDARA", "DSA"),
new Station("DEORIASADAR", "DEOS"),
new Station("DEVLALI", "DVL"),
new Station("DHAMANGAON", "DMN"),
new Station("DHANBAD", "DHN"),
new Station("DHARMABAD", "DAB"),
new Station("DHARMANAGAR", "DMR"),
new Station("DHARMAPURI", "DPJ"),
new Station("DHARMAVARAM", "DMM"),
new Station("DHARWAD", "DWR"),
new Station("DHASA", "DAS"),
new Station("DHAULPUR", "DHO"),
new Station("DHENUANAL", "DNUL"),
new Station("DHOLA", "DLJ"),
new Station("DHONE", "DHNE"),
new Station("DHRANGADHRA", "DHG"),
new Station("DHUBRI", "DBB"),
new Station("DHURI", "DUI"),
new Station("DIBRUGARH", "DBRG"),
new Station("DIBRUGARH TOWN", "DBRT"),
new Station("DIGHA", "DGHA"),
new Station("DILDARNAGAR", "DLN"),
new Station("DIMAPUR", "DMV"),
new Station("DINDIGUL Jn.", "DG"),
new Station("DONGARGARH", "DGG"),
new Station("DORNAKAL", "DKJ"),
new Station("DUNGARPUR", "DNRP"),
new Station("DURG", "DURG"),
new Station("DURGAPUR", "DGR"),
new Station("DUVVADA", "DVD"),
new Station("DWARKA", "DWK"),
new Station("ELURU", "EE"),
new Station("ERNAKULAM Jn.", "ERS"),
new Station("ERNAKULAM TOWN", "ERN"),
new Station("ERODE", "ED"),
new Station("ETAWAH", "ETW"),
new Station("FAIZABAD", "FD"),
new Station("FARIDABAD", "FDB"),
new Station("FARRUKHABAD", "FBD"),
new Station("FATEHABAD CHAND", "FTD"),
new Station("FATEHPUR", "FTP"),
new Station("FATUHA", "FUT"),
new Station("FAZILKA", "FKA"),
new Station("FIROZABAD", "FZD"),
new Station("FIROZPUR CITY", "FZP"),
new Station("FIROZPUR CANTT.", "FZR"),
new Station("FORBESGANJ", "FBG"),
new Station("FURKATING", "FKG"),
new Station("GADAG", "GDG"),
new Station("GAJRAULA", "GJL"),
new Station("GANDHIDHAM", "GIM"),
new Station("GANDHINAGAR", "GADJ"),
new Station("GANGAPUR CITY", "GGC"),
new Station("GARWA ROAD", "GHD"),
new Station("GAYA", "GAYA"),
new Station("GEVRA ROAD", "GAD"),
new Station("GHATSILA", "GTS"),
new Station("GHAZIABAD", "GZB"),
new Station("GOALPARA TOWN", "GLPT"),
new Station("GODHRA", "GDA"),
new Station("GOLA GOKARANNATH", "GK"),
new Station("GONDA", "GD"),
new Station("GONDIA", "G"),
new Station("GOOTY", "GY"),
new Station("GORAKHPUR", "GKP"),
new Station("GOSSAINGAON HAT", "GOGH"),
new Station("GUDIVADA", "GDV"),
new Station("GUDUR", "GDR"),
new Station("GULBARGA", "GR"),
new Station("GUNA", "GUNA"),
new Station("GUNTAKAL", "GTL"),
new Station("GUNTUR", "GNT"),
new Station("GURGAON", "GGN"),
new Station("GURUVAYUR", "GUV"),
new Station("GUWAHATI", "GHY"),
new Station("GWALIOR", "GWL"),
new Station("GYANPUR ROAD", "GYN"),
new Station("HABIBGANJ", "HBJ"),
new Station("HAJIPUR", "HJP"),
new Station("HALDIA", "HLZ"),
new Station("HALDIBARI", "HDB"),
new Station("HAMILTONGANJ", "HOJ"),
new Station("HANUMANGARH", "HMH"),
new Station("HAPA", "HAPA"),
new Station("HAPUR", "HPU"),
new Station("HARDA", "HD"),
new Station("HARIDWAR", "HW"),
new Station("HARIHAR", "HRR"),
new Station("HARPALPUR", "HPP"),
new Station("HASIMARA", "HSA"),
new Station("HATIA", "HTE"),
new Station("HAZUR SAHIB NANDED", "NED"),
new Station("HILSA", "HIL"),
new Station("HIMMAT NAGAR", "HMT"),
new Station("HINDUPUR", "HUP"),
new Station("HINGOLI", "HNL"),
new Station("HISAR", "HSR"),
new Station("HOSHANGABAD", "HBD"),
new Station("HOSPET", "HPT"),
new Station("HOSUR", "HSRA"),
new Station("HOWBADH", "HBG"),
new Station("HOWRAH", "HWH"),
new Station("HUBLI", "UBL"),
new Station("HYDERABAD", "HYB"),
new Station("IGATPURI", "IGP"),
new Station("INDARA", "IAA"),
new Station("INDORE", "INDB"),
new Station("ISLAMPUR", "IPR"),
new Station("ITARSI", "ET"),
new Station("JABALPUR", "JBP"),
new Station("JAGDALPUR", "JDB"),
new Station("JAIPUR", "JP"),
new Station("JAYPUR", "JYP"),
new Station("JAISALMER", "JSM"),
new Station("JAJPUR KEONJHAR ROAD", "JJKR"),
new Station("JAKHAL", "JHL"),
new Station("JALAMB", "JM"),
new Station("JALANDHAR CANTT.", "JRC"),
new Station("JALANDHAR CITY", "JUC"),
new Station("JALGAON", "JL"),
new Station("JALNA", "J"),
new Station("JALPAIGURI", "JPG"),
new Station("JAMALPUR", "JMP"),
new Station("JAMMU TAWI", "JAT"),
new Station("JAMNAGAR", "JAM"),
new Station("JANGHAI", "JNH"),
new Station("JASIDIH", "JSME"),
new Station("JAUNPUR Jn.", "JNU"),
new Station("JAYNAGAR", "JYG"),
new Station("JETALSAR", "JLR"),
new Station("JHAJHA", "JAJ"),
new Station("JHANSI", "JHS"),
new Station("JHARGRAM", "JGM"),
new Station("JHARSUGUDA", "JSG"),
new Station("JIND", "JIND"),
new Station("JODHPUR", "JU"),
new Station("JOGBANI", "JBN"),
new Station("JOLARPETTAI", "JTJ"),
new Station("JORHAT", "JT"),
new Station("JUNAGARH Jn.", "JND"),
new Station("KACHEGUDA", "KCG"),
new Station("KAKINADA PORT", "COA"),
new Station("KALCHINI", "KCF"),
new Station("KALKA", "KLK"),
new Station("KALOL", "KLL"),
new Station("KALYAN", "KYN"),
new Station("KAMAKHYA", "KYQ"),
new Station("KANCHIPURAM", "CJ"),
new Station("KANDHLA", "KQL"),
new Station("KANNIYAKUMARI", "CAPE"),
new Station("KANNUR", "CAN"),
new Station("KANPUR CENTRAL", "CNB"),
new Station("KANPUR ANWARGANJ", "CPA"),
new Station("KAPTANGANJ", "CPJ"),
new Station("KARAIKAL", "KIK"),
new Station("KARAIKKUDI JN.", "KKDI"),
new Station("KARIMGANJ", "KXJ"),
new Station("KARNAL", "KUN"),
new Station("KARUR", "KRR"),
new Station("KARWAR", "KAWR"),
new Station("KASARAGOD", "KGQ"),
new Station("KASGANJ", "KSJ"),
new Station("KATHGODAM", "KGM"),
new Station("KATIHAR", "KIR"),
new Station("KATNI", "KTE"),
new Station("KATNI MURWARA", "KMZ"),
new Station("KATPADI", "KPD"),
new Station("KATWA", "KWAE"),
new Station("KAZIPET", "KZJ"),
new Station("KESINGA", "KSNG"),
new Station("KENDUJHARGARH", "KDJR"),
new Station("KHAGARIA", "KGG"),
new Station("KHALILABAD", "KLD"),
new Station("KHAMMAM", "KMT"),
new Station("KHANDWA", "KNW"),
new Station("KHARAGPUR", "KGP"),
new Station("KHEKRA", "KEX"),
new Station("KHURDA ROAD", "KUR"),
new Station("KHURJA", "KRJ"),
new Station("KISHANGANJ", "KNE"),
new Station("KISHANGARH", "KSG"),
new Station("KIUL", "KIUL"),
new Station("KOCHUVELI", "KCVL"),
new Station("KODAIKANAL ROAD", "KQN"),
new Station("KOLKATA", "KOAA"),
new Station("KOLLAM", "QLN"),
new Station("KOPERGAON", "KPG"),
new Station("KORAPUT", "KRPU"),
new Station("KORBA", "KRBA"),
new Station("KOTA", "KOTA"),
new Station("KOTDWARA", "KTW"),
new Station("KOT KAPURA", "KKP"),
new Station("KOTTAYAM", "KTYM"),
new Station("KOZHIKODE", "CLT"),
new Station("KRISHNANAGAR CITY", "KNJ"),
new Station("KRISHNARAJAPURAM", "KJM"),
new Station("KUMARGHAT", "KUGT"),
new Station("KUMBAKONAM", "KMU"),
new Station("KUNDAPURA", "KUDA"),
new Station("KURDUWADI", "KWV"),
new Station("KURNOOL TOWN", "KRNT"),
new Station("KURUKSHETRA", "KKDE"),
new Station("LAKHIMPUR", "LMP"),
new Station("LAKSAR", "LRJ"),
new Station("LALGARH", "LGH"),
new Station("LALGOLA", "LGL"),
new Station("LALITPUR", "LAR"),
new Station("LALKUAN JN.", "LKU"),
new Station("LATUR", "LUR"),
new Station("LEDO", "LEDO"),
new Station("LOHARU", "LHU"),
new Station("LOKMANYATILAK (T)", "LTT"),
new Station("LONAVLA", "LNL"),
new Station("LONDA", "LD"),
new Station("LOWER HALFLONG", "LFG"),
new Station("LUCKNOW", "LKO"),
new Station("LUDHIANA", "LDH"),
new Station("LUMDING", "LMG"),
new Station("LUNI", "LUNI"),
new Station("MACHILIPATNAM", "MTM"),
new Station("MADARIHAT", "MDT"),
new Station("MADDUR", "MAD"),
new Station("MADGAON (GOA)", "MAO"),
new Station("MADHUBANI", "MBI"),
new Station("MADHUPUR", "MDP"),
new Station("MADURAI Jn.", "MDU"),
new Station("MAHASAMUND", "MSMD"),
new Station("MAHBUBNAGAR", "MBNR"),
new Station("MAHUVA", "MHV"),
new Station("MUNIGUDA", "MNGD"),
new Station("MAHESANA", "MSH"),
new Station("MAHOBA", "MBA"),
new Station("MAILANI", "MLN"),
new Station("MAKSI", "MKC"),
new Station("MALDA TOWN", "MLDT"),
new Station("MANAMADURAI", "MNM"),
new Station("MANDUADIH", "MUV"),
new Station("MANGALORE CENTRAL", "MAQ"),
new Station("MANGALORE JN.", "MAJN"),
new Station("MANIKPUR", "MKP"),
new Station("MANKAPUR", "MUR"),
new Station("MANMAD", "MMR"),
new Station("MANNARGUDI", "MQ"),
new Station("MANSI", "MNE"),
new Station("MANU", "MANU"),
new Station("MARIANI", "MXN"),
new Station("MARWAR Jn.", "MJ"),
new Station("MATHURA", "MTJ"),
new Station("MAU", "MAU"),
new Station("MAYILADUTURAI Jn.", "MV"),
new Station("MEERUT CITY", "MTC"),
new Station("MERTA ROAD", "MTD"),
new Station("METTUPALAYAM", "MTP"),
new Station("MIDNAPORE", "MDN"),
new Station("MIRAJ", "MRJ"),
new Station("MIRYALAGUDA", "MRGA"),
new Station("MIRZAPUR", "MZP"),
new Station("MOGA", "MOF"),
new Station("MOKAMA", "MKA"),
new Station("MORADABAD", "MB"),
new Station("MOTIHARI", "MKI"),
new Station("MUDKHED", "MUE"),
new Station("MUGHALSARAI", "MGS"),
new Station("MUMBAI CENTRAL", "BCT"),
new Station("MUMBAI CST", "CSTM"),
new Station("MUNIGUDA", "MNGD"),
new Station("MURI", "MURI"),
new Station("MURKEONGSELEK", "MZS"),
new Station("MURTAJAPUR", "MZR"),
new Station("MUZAFFAR NAGAR", "MOZ"),
new Station("MUZAFFARPUR", "MFP"),
new Station("MYSORE", "MYS"),
new Station("NABADWIPDHAM", "NDAE"),
new Station("NADIAD", "ND"),
new Station("NADIKUDI", "NDKD"),
new Station("NAGAPPATTINAM", "NGT"),
new Station("NAGARKATA", "NKB"),
new Station("NAGARSOL", "NSL"),
new Station("NAGBHIR", "NAB"),
new Station("NAGDA", "NAD"),
new Station("NAGERCOIL Jn.", "NCJ"),
new Station("NAGORE", "NCR"),
new Station("NAGPUR", "NGP"),
new Station("NAGRAKATA", "NKB"),
new Station("NAINPUR", "NIR"),
new Station("NAJIBABAD", "NBD"),
new Station("NALANDA", "NLD"),
new Station("NALGONDA", "NLDA"),
new Station("NAMAKKAL", "NMKL"),
new Station("NANDALUR", "NRE"),
new Station("NANDGAON", "NGN"),
new Station("NANDURBAR", "NDB"),
new Station("NANDYAL", "NDL"),
new Station("NANGAL DAM", "NLDM"),
new Station("NARKATIAGANJ", "NKE"),
new Station("NARASAPUR", "NS"),
new Station("NARSINGPUR", "NU"),
new Station("NARWANA", "NRW"),
new Station("NASIK ROAD", "NK"),
new Station("NAUGARH", "NUH"),
new Station("NELLORE", "NLR"),
new Station("NETAJI SUBHASH CHANDRABOSE GOMOH", "GMO"),
new Station("NEW ALIPURDUAR", "NOQ"),
new Station("NEW BONGAIGAON", "NBQ"),
new Station("NEW COOCHBEHAR", "NCB"),
new Station("NEW DELHI", "NDLS"),
new Station("NEW FARAKKA", "NFK"),
new Station("NEW JALPAIGURI", "NJP"),
new Station("NEWMAL Jn.", "NMZ"),
new Station("NEW TINSUKIA", "NTSK"),
new Station("NIDADAVOLU", "NDD"),
new Station("NIDAMANGALAM", "NMJ"),
new Station("NIDUBROLU", "NDO"),
new Station("NIMACH", "NMH"),
new Station("NIZAMABAD", "NZB"),
new Station("NIZAMUDDIN", "NZM"),
new Station("NOLI", "NOLI"),
new Station("NORTH LAKHIMPUR", "NLP"),
new Station("ODLABARI", "ODB"),
new Station("OKHA", "OKHA"),
new Station("ONGOLE", "OGL"),
new Station("ORAI", "ORAI"),
new Station("PACHORA", "PC"),
new Station("PALANI", "PLNI"),
new Station("PALANPUR", "PNU"),
new Station("PALASA", "PSA"),
new Station("PALAKKAD", "PGT"),
new Station("PALAKKAD TOWN", "PGTN"),
new Station("PALIAKALAN", "PLK"),
new Station("PANDHARAPUR", "PVR"),
new Station("PANIPAT", "PNP"),
new Station("PARADEEP", "PRDP"),
new Station("PARASNATH", "PNME"),
new Station("PANVEL", "PNVL"),
new Station("PARBHANI", "PBN"),
new Station("PARVATIPURAM TOWN", "PVPT"),
new Station("PATHANKOT", "PTK"),
new Station("PATIALA", "PTA"),
new Station("PATNA", "PNBE"),
new Station("PATNA SAHIB", "PNC"),
new Station("PHALODI", "PLC"),
new Station("PHAPHAMAU", "PFM"),
new Station("PHULERA", "FL"),
new Station("PILIBHIT", "PBE"),
new Station("PIPARIYA", "PPI"),
new Station("PODANUR", "PTJ"),
new Station("PORBANDAR", "PBR"),
new Station("PRATAPGARH", "PBH"),
new Station("PUDUCHERRY", "PDY"),
new Station("PUDUKOTTAI", "PDKT"),
new Station("PULGAON", "PLO"),
new Station("PUNE Jn.", "PUNE"),
new Station("PURANPUR", "PP"),
new Station("PURI", "PURI"),
new Station("PURNA", "PAU"),
new Station("PURNIA", "PRNA"),
new Station("PURULIA", "PRR"),
new Station("RADHIKAPUR", "RDP"),
new Station("RAE BARELI", "RBL"),
new Station("RAICHUR", "RC"),
new Station("RAIGARH", "RIG"),
new Station("RAIPUR", "R"),
new Station("RAJAHMUNDRY", "RJY"),
new Station("RAJA-KA-SAHASPUR", "RJK"),
new Station("RAJA-KI-MANDI", "RKM"),
new Station("RAJENDRANAGAR", "RJQ"),
new Station("RAJGIR", "RGD"),
new Station("RAJKOT", "RJT"),
new Station("RAJNANDGAON", "RJN"),
new Station("RAJPURA", "RPJ"),
new Station("RAMAGUNDAM", "RDM"),
new Station("RAMANATHAPURAM", "RMD"),
new Station("RAMESWARAM", "RMM"),
new Station("RAMNAGAR", "RMR"),
new Station("RAMPUR Jn.", "RMU"),
new Station("RAMPURHAT", "RPH"),
new Station("RANAGHAT", "RHA"),
new Station("RANCHI", "RNC"),
new Station("RANGAPARA NORTH", "RPAN"),
new Station("RANGIYA", "RNY"),
new Station("RANINAGAR", "ROJ"),
new Station("RATANGARH", "RTGH"),
new Station("RATLAM", "RTM"),
new Station("RATNAGIRI", "RN"),
new Station("RAWATGANJ", "RJ"),
new Station("RAXAUL", "RXL"),
new Station("RAYAGADA", "RGDA"),
new Station("RENIGUNTA", "RU"),
new Station("REWA", "REWA"),
new Station("REWARI", "RE"),
new Station("RINGUS", "RGS"),
new Station("ROHTAK", "ROK"),
new Station("ROORKEE", "RK"),
new Station("ROURKELA", "ROU"),
new Station("SADULPUR", "SDLP"),
new Station("SAGAR", "SRF"),
new Station("SAGAULI", "SGL"),
new Station("SAGOUR", "SGO"),
new Station("SAHARANPUR", "SRE"),
new Station("SAHARSA", "SHC"),
new Station("SAHIBGANJ", "SBG"),
new Station("SAI NAGAR SHIRDI", "SNSI"),
new Station("SALEM", "SA"),
new Station("SALEMPUR", "SRU"),
new Station("SAMALKOT", "SLO"),
new Station("SAMASTIPUR", "SPJ"),
new Station("SAMBALPUR", "SBP"),
new Station("SAMBALPUR CITY", "SBPY"),
new Station("SAMDARI", "SMR"),
new Station("SAMUKTALA ROAD", "AMTA"),
new Station("SANGLI", "SLI"),
new Station("SANTRAGACHI", "SRC"),
new Station("SARNATH", "SRNT"),
new Station("SATARA", "STR"),
new Station("SATNA", "STA"),
new Station("SATTENAPALLE", "SAP"),
new Station("SAWAIMADHOPUR", "SWM"),
new Station("SAWANTWADI ROAD", "SWV"),
new Station("SEALDAH", "SDAH"),
new Station("SECUNDERABAD", "SC"),
new Station("SENGOTTAI", "SCT"),
new Station("SENSOA", "SCF"),
new Station("SEWAGRAM", "SEGM"),
new Station("SHAHABAD", "SDB"),
new Station("SHAHGANJ", "SHG"),
new Station("SHAHJAHANPUR", "SPN"),
new Station("SHAHPUR PATOREE", "SPP"),
new Station("SHAKTINAGAR", "SKTN"),
new Station("SHALIMAR", "SHM"),
new Station("SHAMGARH", "SGZ"),
new Station("SHAMLI", "SMQL"),
new Station("SHIKOHABAD", "SKB"),
new Station("SHIMLA", "SML"),
new Station("SHIMOGA TOWN", "SMET"),
new Station("SHIVPURI", "SVPI"),
new Station("SHORANUR Jn.", "SRR"),
new Station("SHRI MAHABIRJI", "SMBJ"),
new Station("SIHOR GUJARAT", "SOJN"),
new Station("SIKAR", "SIKR"),
new Station("SILCHAR", "SCL"),
new Station("SILGHAT", "SHTT"),
new Station("SILIGURI", "SGUJ"),
new Station("SILIGURI TOWN", "SGUT"),
new Station("SIMALUGURI", "SLGR"),
new Station("SINGRAULI", "SGRL"),
new Station("SIRPUR KAGAZNAGAR", "SKZR"),
new Station("SIRSA", "SSA"),
new Station("SISWA BAZAR", "SBZ"),
new Station("SITAMARHI", "SMI"),
new Station("SITAPUR CITY", "SPC"),
new Station("SITAPUR CANTT.", "SCC"),
new Station("SIURI", "SURI"),
new Station("SIWAN", "SV"),
new Station("SOJAT ROAD", "SOD"),
new Station("SOLAN", "SOL"),
new Station("SOLAPUR", "SUR"),
new Station("SOMNATH", "SMNH"),
new Station("SOMPETA", "SPT"),
new Station("SONPUR", "SEE"),
new Station("SRI CHHATRAPATI SHAHU MAHARAJ (T)", "CSMT"),
new Station("SRI DUNGARGARH", "SDGH"),
new Station("SRIGANGA NAGAR", "SGNR"),
new Station("SRIKAKULAM ROAD", "CHE"),
new Station("SRI SATHYASAI PRASHANTI NILAYAM", "SSPN"),
new Station("SUJANGARH", "SUJH"),
new Station("SULTANPUR", "SLN"),
new Station("SURAT", "ST"),
new Station("SURATGARH", "SOG"),
new Station("SURATHKAL", "SL"),
new Station("SURENDRA NAGAR", "SUNR"),
new Station("TADEPALLIGUDEM", "TDD"),
new Station("TAMBARAM", "TBM"),
new Station("TATANAGAR", "TATA"),
new Station("THALASSERY", "TLY"),
new Station("TENALI", "TEL"),
new Station("TENKASI", "TS"),
new Station("TEZPUR", "TZTB"),
new Station("THANJAVUR", "TJ"),
new Station("THIRUVARUR", "TVR"),
new Station("TIRUCHIRAPPALLI Jn.", "TPJ"),
new Station("TIRUCHENDUR", "TCN"),
new Station("TIRUNELVELI", "TEN"),
new Station("TIRUPATI", "TPTY"),
new Station("TIRUPPUR", "TUP"),
new Station("TIRUR", "TIR"),
new Station("TITLAGARH", "TIG"),
new Station("THRISUR", "TCR"),
new Station("THIRUVANANTHAPURAM", "TVC"),
new Station("TIRUVANNAMALAI", "TNM"),
new Station("TUMSAR ROAD", "TMR"),
new Station("TUNDLA", "TDL"),
new Station("TUNI", "TUNI"),
new Station("TUTICORIN", "TN"),
new Station("UDAIPUR CITY", "UDZ"),
new Station("UDHAMPUR", "UHP"),
new Station("UDHNA", "UDN"),
new Station("UDUPI", "UD"),
new Station("UJJAIN", "UJN"),
new Station("UNA", "UNA"),
new Station("UNCHAHAR", "UCR"),
new Station("UNNAO", "ON"),
new Station("VADAKARA", "BDJ"),
new Station("VADODARA", "BRC"),
new Station("VALSAD", "BL"),
new Station("VANCHI MANIYACHCHI Jn.", "MEJ"),
new Station("VARANASI", "BSB"),
new Station("VARKALA", "VAK"),
new Station("VASAI ROAD", "BSR"),
new Station("VASCO-DA-GAMA", "VSG"),
new Station("VELANKANNI", "VLKN"),
new Station("VERAVAL", "VRL"),
new Station("VIDISHA", "BHS"),
new Station("VIJAYAWADA", "BZA"),
new Station("VILLUPURAM Jn.", "VM"),
new Station("VIRAMGAM", "VG"),
new Station("VIRUDUNAGAR Jn.", "VPT"),
new Station("VISAKHAPATNAM", "VSKP"),
new Station("VIZIANAGARAM", "VZM"),
new Station("VRIDDHACHALAM Jn.", "VRI"),
new Station("WADI", "WADI"),
new Station("WANKANER", "WKR"),
new Station("WARANGAL", "WL"),
new Station("WARDHA Jn.", "WR"),
new Station("YESVANTPUR", "YPR"),
new Station("ZAFARABAD", "ZBD"),





            // Add more stations as needed
        };
    }
}
